# SSB Metrics Index Table 

Below is a list of the metrics generated by SSB and the product chapter to which they correspond.

## Reading the Table
### Table Columns
* **Metric Category** - The broader social or economic metric category in which the metric pertains

* **Metric** - The statistic, measure, or indicator which is created by SSB

* **Data Output Source** - The SSB product where the metric is featured

* **Summary Groups** - The level at which the metric is presented (e.g., Fishery Management Plan or Gear-group level)

* **Time Series** - The temporal scale at which the metric is presented  

### Summary Group Descriptions

* **Aggregate FMP-level** - Data summarized for all New England and Mid-Atlantic Fisheries Management Programs (FMPs) combined. 

* **FMP-level** - Data summarized by individual New England Fisheries Management Programs (FMPs) (e.g., )

* **Gear type-level** - Data summarized by gear group (E.g., revenue earned for all gillnet trips or vessels). See individual product chapters for how gear was determined at the trip or vessel level (for example, trips or vessels are usually binned into specific gear categories based on the gear used to earn the most revenue for a trip or vessel)

### Time Series Descriptions

* **Most Recent Year** - This indicates that there is one year of data for which the metric is summarized. It corresponds to the most recent year in which the code was run for that metric, not the most recent calendar year.

```{r metrics-table, echo=FALSE, message=FALSE, warning=FALSE}
library(readxl)
library(dplyr)
library(tidyr)
library(kableExtra)

# 1. Read the file
df <- read_excel("C:/Users/samantha.l.werner/Desktop/Github/READ-SSB-SSB_METRICS_CATALOG/Index_table.xlsx") 

# 2. Repair ONLY empty names to avoid the 'zero-length' error while keeping spaces in others
colnames(df)[colnames(df) == ""] <- "Unnamed"

# 3. Process and Render
df %>%
  # Use backticks `` for names with spaces
  fill(`Metric Category`, .direction = "down") %>% 
  filter(!is.na(Metric)) %>% 
  kbl(
    booktabs = TRUE, 
    align = "l", 
    longtable = TRUE,
    # Define the display names here to get rid of the periods
    col.names = c("Metric Category", "Metric", "Data Output Source", "Unit", "Summary Group(s)", "Time Series"),
    caption = "Economic and Social Performance Metrics Overview"
  ) %>%
  kable_styling(
    bootstrap_options = c("striped", "hover", "bordered", "condensed"),
    full_width = FALSE
  ) %>%
  collapse_rows(columns = 1, valign = "middle") %>%
  # Adds the scrollable feature with a fixed header
  scroll_box(width = "100%", height = "500px", fixed_thead = TRUE)
```

