# Performance Measures Website


## Product Overview
Performance Measures website, managed by the Social Sciences Branch of the NEFSC, provides a public, data-driven overview of the economic and social performance of various Northeast Fishery Management Plans (FMPs). The site tracks and displays critical indicators of a fishery’s health and economic impact.

* Unit - Active vessels 
* Summary Group(s) -  Primary FMP 
* Frequency - Updated annually 
* Time Series - Annual (2007-2024)* 
  *the time series goes to the most recent year for which the code is run and updated regularly  

### Point of Contact
Chad Demarest (Chad.Demarest@noaa.gov)

### Data Outputs/Outlets
Code below used to create the  [Performance Measures Website ](https://apps-nefsc.fisheries.noaa.gov/pm/index.php)


## List of Metrics 

### All NE FMP plans combined metrics
* Total vessels
* Total trips
* Total DAS
* Total FMP revenue 

### FMP-level Metrics 
* Revenue
* Average Prices
* Revenue per vessel
* Number of vessels
* Revenue per trip
* Number of trips
* Revenue per Days at Sea
* Number of Days at Sea
* Gini Coefficient 


## Metric Descriptions 

### All NE FMP plans combined metrics
* Total Vessels
  * Description: Number of uniquely identified vessels that took a fishing trip in a calendar year.
* Total Trips 
  * Description: The sum of trips from each FMP in a calendar year. See definition of trips in a FMP below.
* Days at Sea 
  * Description: The sum of days at sea from each FMP in a calendar year. See definition of Days at Sea in a FMP below.
* FMP Revenue 
  * Description: The sum of total revenue earned from each FMP fishery. See definition of revenue in a FMP below.
  
### FMP-Specific Metrics
* Vessels 
  * Description: Number of vessels that take at least one trip where more than 50% of its revenue comes from species included in the FMP.
* Trips  
  * Description: Total trips taken in the FMP fishery. A trip is identified as having participated in the fishery if greater than 50% of the revenue for the trip was derived from FMP species.
* Days at Sea
  * Description: Time from when a vessel leaves port to when it returns on a trip in the FMP fishery. This metric is the sum of all days at sea by all vessels taking a trip in the FMP. The calculation of this metric does not include any demarcation lines.
* Revenue 
  * Description: For each year, the sum of total deflated revenue from species in the FMP fishery (FMP Revenue) and the revenue from other species landed on trips identified as being in the fishery (Non-FMP Revenue).
* Average Prices
  * Description: For each species in the FMP, this is an implicit price calculated as total deflated revenue divided by total landed pounds.
* Revenue per Vessel 
  * Description: For each vessel included in the FMP data, deflated revenue is divided into FMP revenue and non-FMP revenue. Per vessel revenue is calculated as the total revenue in each category divided by the total vessels in each year.
* Total Revenue per Trip 
  * Description: Total deflated revenue from FMP and non-FMP species divided by the total number of trips identified as having taken place in the fishery.
* Revenue per Day at Sea
  * Description: Total deflated revenue from both FMP and non-FMP species landed, divided by the total number of days absent on trips in the fishery.
* Gini Coefficient 
  * Description: A measure of revenue inequality in the fishery, and can range between 0 (perfect equality) and 1 (perfect inequality). Perfect inequality means that one entity receives all the revenue from the fishery.
  * Equation: G = Σ (2in - 1)xi / 2nū 
  * Where: i = vessel's rank in revenue in ascending order xi = annual revenue in the fishery for vessel i n = total number of vessels ū = mean vessel revenue

## Additional Methods/Decision Rules 

### Summary Group Decision Rules
FMP defined as at least one trip where more than 50% of its revenue comes from species included in the FMP.

### Deflation
All dollar values have been deflated using the GDP implicit price deflator, deflating prices to constant dollars for the most recent year where data from the BEA is provided. Deflation code can be found in the website product code. 

### Matching Trips (veslog - cfders)
We match trip and dealer records by vtrserno/serial_num.

### Binning Rules
A trip is assigned to an FMP based on the highest FMP revenue value.

### Average Prices
We are only using the average prices for trip records which didn't have a matching dealer record. For the ones that do, we use the calculated prices from the dealer record.

### Exclusions
 1. If vtrserno is a match, but permit = '000000', the trip is considered again when looking at orphan trips
 2. Mismatched trips (multiple vtrserno corresponding to one tripid, and one(or more) vtrserno has a match, but other(s) do not) are not included in the orphan trips group
 
### Outliers
 Revenue per Trip metric is used to identify outliers.
 Outlier removal is based on interquartile test
*First, Lower (<=0.25) and Upper (>=0.75) Quartile and calculated. Then, the lower bound for determining an outlier is lq-1.5*(uq-lq), and the upper bound is uq+1.5*(uq-lq). Any values less than the lower bound or greater than the upper bound are removed.

## Data Sources and Code 

### Data Sources 
CFDBS
VTR
SFCLAM

### Code
Metric Creation Code File Location
https://github.com/NEFSC/READ-SSB-PM
(Permissions required)
Read Me file (file to run code): https://github.com/NEFSC/READ-SSB-PM\README.md (Permissions required)

Website Production Code Location: https://github.com/NEFSC/READ-SSB-PM 
(Permissions required)
Read Me file (file to run code): https://github.com/NEFSC/READ-SSB-PM/blob/main/README.md
(Permissions required)

