# 2022 Vessel Profit snapshot website 

## Product Overview
This site presents commercial fishing vessel profits during 2022 for vessels who responded to the Greater Atlantic Region Commercial Fishing Business Cost Survey 
* Unit:  Vessel-level information (responding vessels only) 
* Summary Group(s): Primary gear type, FMP and gear of responding vessels 
* Frequency: Annual 
* Time Series: Snapshot (2022)

### Point of Contact 
Gregory Ardini (Gregory.Ardini@noaa.gov)

### Data Outputs/Outlets 
https://ardini-noaa.github.io/2022_Vessel_Profit_Snapshots/

## List of Metrics 
* Revenue
* Costs
* Operating profit
* Total profit 

## Metric Descriptions 
* Revenue 
  * Commercial revenue
  * All individuals that were sampled for the 2022 cost survey were owners of federally-permitted commercial fishing vessels active in 2021 or 2022. Federally-permitted vessels are required to sell their catch to federally-licensed seafood dealers and commercial revenue is derived from harvested catch on commercial trips sold to a licensed dealer. All vessels included in the profit snapshots generated commercial fishing revenue >$0 during 2022 from landings occurring in the Northeast region (ME to Cape Hatteras, NC).
  * The values reported by dealers feed into the Catch Accounting and Monitoring System (CAMS) housed at the Greater Atlantic Regional Fisheries Office (GARFO) and the NEFSC. Vessel revenues are queried directly from CAMS with two exceptions. The first is for cases in which there is a reported commercial landing volume in CAMS but no associated value. For these observations, prices were generally imputed as the average species price for 2022 to calculate value (landings*price). If the observation had a dealer disposition code in which a value is not expected (e.g. “No market”, “Personal Use”) then values were left blank. In total, 3.6% of observations used an imputed price rather than a dealer reported price. The second exception is for revenue derived from bluefin tuna as the reporting requirements for this species differs from other species landed in the Northeast region. Bluefin tuna revenue was queried from the Atlantic Coastal Cooperative Statistics Program (ACCSP) data warehouse, while all other species revenue was queried from CAMS.
* For Hire revenue

    * While the 2022 cost survey was sent to vessels engaged in commercial fishing during 2021 or 2022, some of these vessels also were engaged in for-hire fishing. In order to accurately capture vessel-level profits, it is important to include this additional source of revenue. For-hire revenue is derived from angler/customer payments on recreational trips. All 2022 party/charter trips, and the number of anglers per trip, were first pulled from logbook data. Average angler charter/guide fees by state were then retrieved from the results of the 2022 National Angler Expenditure Survey administered by NOAA Fisheries. This survey is conducted every 3-5 years to better understand the economic contribution of recreational fishing within each region. The survey collects information on a variety of angler expenditures including bait, ice, lodging, and travel costs. For the purpose of the vessel profit calculation, only the amount paid by the angler for the party/charter ticket is used. State-level averages from the angler expenditure survey were used in light of the variability in fees by state within the Northeast region as well as the high level of response for each state. The average angler fee was multiplied by the number of anglers for each 2022 party/charter trip by state. Finally, the trip-level calculations were summed to an annual vessel-level value.

* Costs 
  * Description: 
    * New/Replacement, Repair/Maintenance, and Upgrade Costs for the Selected Vessel
      * Propulsion Engine
      * Seine Skiff (Seine survey version only)
      * Deck Equipment / Other Machinery
      * Haul-out Costs
      * Hull
      * Fishing Gear
      * Wheelhouse Electronics
      * Processing / Refrigeration
      * Safety Equipment
      * Vessel Costs for the Selected Vessel
      * Mooring/Docking Fees
      * IFQ Cost Recovery Fees (Scallop Dredge survey version only)
      * State and Federal Permits and/or License Renewal Fees
      * Launch and Trailer Fees (Handgear survey version only)
      * Annual Vessel Insurance Premium
    * Trip Expenses for the Selected Vessel
      * Fuel
      * Bait
      * Food for captain and crew
      * Ice
      * Catch Handling- costs for auction, lumping, grading, shipping/trucking, and unloading.
      * At-sea Processing At-sea Boxing/Packaging
      * Paralytic Shellfish Poison Testing (Hydraulic Dredge survey version only)
    * Crew Payment System for the Selected Vessel
      * Total Payments to Crew
      * Total Payments to Hired Captain
      * Benefits Paid to Crew and/or Hired Captain
    * Overhead Costs
      * Business Vehicle Costs
      * Business Travel Costs
      * Association Fees
      * Legal Expenses
      * Additional Labor Payments
      * Advertising Costs
      * Communication Costs
      * Office/Workshop/Storage Expenses
      * Spotter Planes, Drones or Other Aerial Search Expenses (Seine survey version only)
    * Quota Costs and Revenues for the Selected Vessel
      * Quota Leasing Costs
      * Quota Leasing Revenue
      * Quota Monitoring Costs
    * Other Costs for the Selected Vessel

  * From these various cost categories within the survey, some data manipulation was required to make costs usable at the vessel/annual level. These data manipulation steps are summarized below.

  * Trip Expenses Survey respondents were given the option of providing trip expenses either at the annual level or as a trip average. For those respondents who filled in the average cost per trip, the value was multiplied by the number of commercial trips taken during 2022. In general, the number of trips was used directly from the survey (Q2). In cases where this information was not filled in, the number of trips was retrieved from VTRs and/or dealer reports. Trip expenses were then allocated to the vessel owner based on how the survey respondent indicated these expenses were paid (Q6). If the respondent answered that the crew paid for trip expenses, the assigned cost to the vessel owner was $0. If the respondent answered that the boat/owner paid for trip expenses, 100% of these costs were assigned to the vessel owner. If the respondent answered that trip expenses were shared between boat/owner and crew, these costs were multiplied by the % indicated for the vessel owner to assign these costs.
Overhead Costs: Survey respondents were given the option of providing these costs either at the vessel level or at the business level. For those respondents who filled in business level costs, the value was divided by the number of vessels owned by the respondent during 2022. The number of vessels owned was taken directly from the survey (Q13).

  * Quota Costs and Revenues: Survey respondents were given the option to provide quota leasing costs either at the vessel-level or across multiple vessels. If this cost was provided across multiple vessels, the value was divided by the specific number of vessels the quota leasing cost was attributed to (Q17). Similar to trip expenses, quota leasing costs were then allocated to the vessel owner based on how the survey respondent indicated these expenses were paid (Q18). If the respondent answered that the crew paid for trip expenses, the assigned cost to the vessel owner was $0. If the respondent answered that the boat/owner paid for trip expenses, 100% of these costs were assigned to the vessel owner. If the respondent answered that trip expenses were shared between boat/owner and crew, these costs were multiplied by the % indicated for the vessel owner to assign these costs. Quota leasing revenue was then subtracted from costs to calculate net quota leasing costs to the vessel. Quota leasing occurs within the groundfish, sea scallop, surf clam/ocean quahog, and tilefish fisheries. Due to net quota leasing representing a small portion of total costs for the various fleets presented on this site, these costs are not included in the cost distribution summaries found in Chapter 7. However quota net leasing costs are included in total profit profiles found in Chapter 9.

  * Other Costs: At the end of the survey, respondents were given the opportunity to list other costs that were not included in the survey. When other costs were listed, they were evaluated on a case-by-case basis. When deemed possible, other costs listed were allocated to an existing cost category. Those that could not be allocated to an existing cost category were excluded from the profit calculation. Examples of costs that were able to be allocated to an existing category include registration fees were added to Permit Fees and non-descript vessel repairs/maintenance were allocated evenly across the various repair/maintenance categories.

  * Two costs, crew supplies and fresh water, that are collected by at-sea observers that were not included in the 2022 cost survey. To capture these costs, data from observer programs was used to calculate average costs per trip by gear. All 2022 trips from observer data tables were pulled, along with the primary gear utilized on each trip. The average crew supply and fresh water trip costs by gear type were calculated and these averages were then merged by gear with all of the trips taken by survey responding vessels during 2022. Finally, trip-level costs were summed to the vessel-level.

* Operating profit
  * Operating profit refers to gross revenues minus operating costs (variable costs). Within the 2022 cost survey, two sections in particular cover operating costs. The trip expenses section collects information on fuel, bait, ice, and food. The crew payment section includes the total amount paid to crew and hired captains, as well as any benefits paid out. Outside of the survey, a few costs collected by at-sea observers, fresh water and crew supplies, are also included in the operating profit calculation.
  * Equation: Gross Revenue - (Trip Expenses + Crew Payments)

* Total profit 
  * Total profit refers to operating profit minus non-operating costs (fixed and quasi-fixed costs). Within the 2022 cost survey, a few different sections include non-operating costs. The vessel repairs and upgrades section (#2) includes the amount spent on various vessel components including the engine, hull, fishing gear, electronics, and safety equipment. The vessel costs section (#3) factors in mooring fees, permit fees, and vessel insurance. The overhead section (#6) includes, among other costs, business vehicle expenses, association fees, non-crew labor payments, and office/storage expenses. The quota costs and revenue section (#8) is also included as a component of non-operating costs. Lastly, depreciation is estimated from the vessel values section (#7).
  * Equation: Operating Profit - (RMUI/other + Vessel Costs + Overhead + Quota Leasing + Depreciation)

## Additional methods/decision rules

### Summary Group Decision Rules 
#### Primary Gear 
Vessel primary gear is defined according to the largest contributor to total commercial vessel revenue during 2022. Fishing gears, primarily from Vessel Trip Reports (VTRs) were grouped into the same categories as used for the 2022 cost survey sampling frame. For example, bottom trawl and midwater trawl were grouped into a broader trawl category. The resulting primary gear groups are as follows: gillnet, handgear, hydraulic dredge, longline, pot/trap, scallop dredge, seine, trawl, and unknown. Due to low response levels for some primary gear groups, results are unable to be presented. The scale of vessel operations, as indicated by revenues and costs, is influenced by vessel characteristics. As such, the Cost Data Visualization Tool is a helpful reference for certain characteristics by gear (e.g. vessel length and average crew) for respondents to the 2022 cost survey.
As a sensitivity test, results were examined under the scenario of gear only being defined if 100% of the vessel’s revenue was generated from that gear during 2022. In general, results were similar to those presented on this site.
#### Primary Fishery
Vessel primary fishery is also defined as the largest contributor to total commercial vessel revenue during 2022. Species were grouped into Fishery Management Plans (FMPs) as managed by the New England and Mid-Atlantic Fishery Management Councils, as well as American lobster, managed by the Atlantic States Marine Fisheries Commission. A few other fisheries (channeled whelk, highly migratory species, striped bass) are also included in summary tables due to sufficient response of at least 3 vessels. Fisheries with at least 5 responding vessels are also included in boxplots. A few other fisheries received low response levels and results are unable to be presented. As a sensitivity test, results were examined under the scenario of fishery only being defined if 100% of the vessel’s revenue was generated from that fishery during 2022. In general, results were similar to those presented on this site.
#### Primary Gear/Fishery
 Vessel primary gear and primary fishery were also combined to examine differences within more specific fleets. For most gear types, multiple fisheries are represented. However, scallop dredge gear, for example, is represented by only one fishery (sea scallop). Due to low response levels for some primary gear/fisheries, results are unable to be presented.

### Depreciation
The final cost component included in the profit calculation is vessel depreciation. Ideally, a different depreciation value would be assigned to each physical capital component (e.g. electronics, engine, hull) using the estimated market value and age of each piece of vessel equipment. This method would require additional information beyond that collected in the 2022 cost survey.
Information on the estimated market vessel value, including all equipment and fishing gear, was collected in the 2022 cost survey. However the number of responses to this question were lower than other survey questions explained in part by the inclusion of a “I prefer not to answer” option, which was not included for other survey questions. Given the relative lack of response for vessel market value, an alternate method was used in which shadow values of vessel characteristics including age, gross tonnage, length, and type of construction were estimated. The shadow values were then multiplied by each vessel characteristic to calculate a total vessel value. From the vessel values, a depreciation cost was calculated as 4% of the value for those vessels less than 25 years old and 2% of the value for those vessels 25 years or older following methods utilized for fishing fleets in Kitts et al. (2020).

## Data Sources and Code
### Data sources
Cost Data -  (data originally used from flat file but has since been database to Oracle via SSB_COST_SURVEY.VCS_COMMON_VARIABLES_MV 
Revenue - CAMS 

### Code
Metric Creation Code Files https://github.com/Ardini-NOAA/2022_Vessel_Profit_Snapshots/tree/main/scripts_to_generate_input_files 
Read Me file (file to run code): N/A
Website Production Code Location: https://github.com/Ardini-NOAA/2022_Vessel_Profit_Snapshots
Read Me file (file to run code): https://github.com/Ardini-NOAA/2022_Vessel_Profit_Snapshots/blob/main/README.md


