# Regulatory Flexibility Act (RFA) Vessel Owner Affiliate Dataset 
This file presents metrics by “affiliate”, which comprise business “entities”. These data are assembled for analysis required by the Regulatory Flexibility Act. Fishing vessels (permits) are linked together, an industry determination is made, and firms are classified as small or large based on SBA guidelines. Per SBA guidelines, we use revenue data in a single year to make the industry determination. Per SBA guidelines, we use 5 year trailing average to make the "small" determination.

## Product Overview
* Unit: 
Affiliate
* Summary Group(s): 
N/A
* Frequency: 
Annual 
* Time Series:  
Most recent year (information lagged over five years to create groups)

### Point of Contact
Min-Yang Lee (Min-Yang.Lee@noaa.gov)
### Data Outputs/Outlets 
Data is not hosted on a website but the dataset is stored on the socialsci share drive at : \\nefscfile\RFA_EO12866_Guidelines\Ownership Data.  There, you will find current data, archived data, and background information.

## List of metrics 

  * affiliate_id
  * year
  * count_permits
  * entity_type_YYYY-1
  * small_business
  * permit
  * affiliate_total
  * affiliate_fish
  * affiliate_forhire
  * value_permit
  * value_permit_forhire
  * valueNNN
  * person_idY
  * PLAN_CAT


## Metric Descriptions

| Column | Type | Definition |  
|---|---|---|
|affiliate_id|    float|   Key that identifies an entity in this dataset. Not consistent across data vintages. See Warning 3 below. | 
|year|            int |   Calendar year corresponding to revenue and value columns.  | 
|count_permits|   byte |  Number of distinct permits owned by an entity in year YYYY.|               
|entity_type_*YYYY-1* | string7| The type of entity ("FISHING", "FORHIRE", "NO_REV") based on the source majority of revenues in the previous year. If a firm had zero revenues in year YYYY-1, then it is classified as "NO_REV"|                 
|small_business|  byte |  =1 if a firms is a small business, =0 otherwise.|             
|permit|          long|   permit number | 
|affiliate_total| float|  total revenues for the affiliate in a year |           
|affiliate_fish|  float|  commercial fishing revenues for the affiliate in a year |              
|affiliate_forhire| float| for-hire revenues for the affiliate in a year|               
|value_permit|    float|  value of revenues, all sources, for the **permit** in a year|           
|value_permit_forhire| float|value of for-hire revenues for the **permit** in a year|          
|value*NNNNNN* | float| value of commercial revenues for the **permit** in a year from the ITIS_TSN code NNNNNN|          
|person_id*Y* | int | The person_id of an owner. For a row of data, these are arranged in increasing order of person_id |          
|PLAN_CAT | byte | =1 if a vessel held a permit of "PLAN" and "CAT", =0 otherwise |  

## Additional methods/decision rules 


### Updates

We run this code to provide data once a year, just after June 1st.  If critical bugs are found, we will fix and update.

### Data Overview

Each row contains an observation of a permit-year.  Permits are grouped together through common ownership; vessels with identical owners have the same affiliate_id.  There are three affiliate level columns: *affiliate_total*, *affiliate_fish*, and *affiliate_forhire* revenue.  These columns contain the aggregate revenue, commercial fishing revenue, and for-hire revenue for the firm.  The following table is an example:

affiliate_id|	year|	count_permits|	entity_type_YYYY-1|	small_business |	permit|	affiliate_total|	affiliate_fish| value_permit
|---|---|---|---|---|---|---|---| ---|
1	|2017|	1|	FISHING|	1|	999999|	1675310|	1675310| 1675310
1	|2018|	1|	FISHING|	1|	999999|	1625835|	1625835|1625835
1	|2019|	1|	FISHING|	1|	999999|	1725104|	1725104|1725104
2	| 2017|	2|	FISHING|	1|	111111|	**2830508**|	**2830508**|*1240510*
2|	2017|	2|	FISHING|	1|	222222|	**2830508**|	**2830508**|*1589998*

We use permit and ownership data from the current year (**ap_year= YYYY**) to link together permits into firms.  We use permit holdings on **June 1**  of the **current year** to construct the PLAN_CAT variables.  These take on the value of "1" if a permit held a **PLAN_CAT** and 0 otherwise. These may be useful to quickly determine if an entity is regulated.  We use dealer plus clam processor report data from years **YYYY-5** through year **YYYY-1** to construct commercial revenues.  VTR data combined with recreational survey data are used to construct for-hire revenues.

Analysis required by the Regulatory Flexibility Act should use the Affiliate_id, year, and permit fields to correctly group fishing vessels into entities.  All other data is provided as a convenience.

The firm is classified as a Commercial Fishing ("FISHING"), For-Hire ("FORHIRE"), or "NO_REV" based on the breakdown of revenues **in year YYYY**. 


### Dollar Values 
All revenue and value figures are in nominal terms.

### Warnings
1. Do not sum the affiliate revenue variables.  You will not get the total revenues.  If you want aggregate revenues for a fleet, you should either:
    1. Retain only the distinct AFFILIATE_ID and YEAR entries and SUM the affiliate revenue columns, or 
    2. Sum the value_permit, value_permit_forhire, or valueSSS columns

2. There is no guarantee that permits that were affiliated in a particular year were also affiliated in previous years.  
For example, the fact that permits 123 and 456 were affiliated in 2013, does not imply that they were affiliated in 2012.

3.  Once a group of permits is affiliated together, revenues for the trailing 5 years are combined and aggregated.  
For example, if permits 123 and 456 were affiliated in 2022 but not from 2017-2021, the revenues for 123 and 456 across the 2017-2021 period averaged when making a SBA size determination.  This is consistent with current SBA guidance.

4. When the dataset is generated for subsequent years, the affiliate id variables will change.  For example if permits 123 and 456 were affiliate_id =3 in 2021, that same grouping (if it even exists) is likely to have a different value of affiliate_id in 2022.  This is probably fine for RFA purposes.

5.  If a business is owned by another business, you won't see the people in the company in bus_own. The people in this situation are one or more levels below the first owner record and thus don't show up in bus_own. We don't have many businesses like this, but there are few. This means that the dataset does not combine as many firms as it should. Therefore, there are probably more firms and small firms that in reality.

6. The YYYY-1 part of Entity_type_YYYY-1 is slightly confusing. 

### Additional Metadata
Additional metadata on running the code is found here: https://github.com/NEFSC/READ-SSB-Lee-RFAdataset/blob/edc226a46fca1482ec0238c31e06a2f3da03309c/documentation/output_documentation/output_data_description.md

## Data Sources and code 

### Data Sources 
VTR
CFDBS
PERMITS

### Code
Code for generating the dataset found here: 
https://github.com/NEFSC/READ-SSB-Lee-RFAdataset
Readme file associated with running the code: N/A
